# Generated by Django 6.0 on 2025-12-26 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAFiles', '0002_alter_hoagroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hoa_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HOAFiles.hoagroup')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
