# Generated by Django 6.0 on 2025-12-26 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAFiles', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOAMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hoa_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='HOAFiles.hoagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hoa_memberships',
                'unique_together': {('user', 'hoa_group')},
            },
        ),
    ]
