# Generated by Django 6.0 on 2025-12-26 20:31

from django.db import migrations


def migrate_memberships_forward(apps, schema_editor):
    """
    Migrate existing ManyToMany relationships to HOAMembership.
    Users whose email matches owner_email become admin, others become members.
    """
    HOAGroup = apps.get_model('HOAFiles', 'HOAGroup')
    HOAMembership = apps.get_model('HOAFiles', 'HOAMembership')
    User = apps.get_model('HOAFiles', 'User')

    for hoa_group in HOAGroup.objects.all():
        # Get existing users from the old ManyToMany (before through model)
        for user in hoa_group.users.all():
            # Check if user email matches owner_email to determine admin role
            role = 'admin' if user.email == hoa_group.owner_email else 'member'
            HOAMembership.objects.get_or_create(
                user=user,
                hoa_group=hoa_group,
                defaults={'role': role}
            )


def migrate_memberships_reverse(apps, schema_editor):
    """Reverse migration - clear HOAMembership table"""
    HOAMembership = apps.get_model('HOAFiles', 'HOAMembership')
    HOAMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('HOAFiles', '0004_hoamembership'),
    ]

    operations = [
        migrations.RunPython(
            migrate_memberships_forward,
            migrate_memberships_reverse
        ),
    ]
