# Generated by Django 6.0 on 2025-12-26 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOAFiles', '0005_migrate_memberships'),
    ]

    operations = [
        # Remove the old ManyToMany field (the intermediate table hoa_groups_users)
        migrations.RemoveField(
            model_name='hoagroup',
            name='users',
        ),
        # Add the new ManyToMany field with through model
        migrations.AddField(
            model_name='hoagroup',
            name='users',
            field=models.ManyToManyField(related_name='hoa_groups', through='HOAFiles.HOAMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
